### ISSUE TITLE
LineChart and BarChart sizing causes jumping effect with scrollbar on parent

### ISSUE THREAD

**Issue by gwatts-klipfolio** [stripe/stripe-apps#647] opened 2022-06-13 20:10 UTC
**Describe the bug**

Because the LineChart and BarChart resize in a way that preserves their aspect ratio (which does not seem to be configurable) it can cause jumping issues when the parent component has an overflow of auto on Windows.

The issue has to do with the fact that scrollbars on Windows take some of the rendering width of the component. The issue occurs when the size of the parent (usually due to the size of the browser window) is such that it requires a vertical scrollbar to render the content when there is no scrollbar, but after displaying the scrollbar and shrinking the width a little (also shrinks the height a little because of the aspect ratio) it no longer needs a scrollbar. This causes the browser to jump back and forth between showing the scrollbar and not showing the scrollbar.

**To Reproduce**
1. Inside a ContextView add at least one chart in a box. Ex:

```
<Box css={{ layout: 'column', width: 'fill' }}>
      <LineChart
        data={...}
        x={...}
        y={...}
        color={...}
        axis="y"
        grid="y"
        legend={false}
      />
</Box>
```

2. On a windows machine, shrink the browser to the point just after the scrollbar appears. The issue should start occurring as the chart changes width and height each time the scrollbar appears or disappears.

**Expected behaviour**

There should be a way to set the chart so that it does not size this way to avoid this type of issue. Possibly by setting height and width separately.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Comment by dannygarcia-stripe** [comment] 2022-06-13 21:41
Investigated and replicated on mac as well. Moving to DS since it seems like a Chart <> Drawer bug.

**Comment by ericfrank-stripe** [comment] 2022-10-27 17:57
This issue should be fixed now, no SDK update required. If you're able to reproduce, please post here and we'll reopen the issue.

**Closed by ericfrank-stripe** 2022-10-27 17:57 UTC
Labels: bug, design-system

**Comment by SpecialKREDhat** [comment] 2022-11-01 21:11
Hello, thank you for the advice, and as I stated before. The link into the app is still under development. I prefer to use a different app to link payment honestly. I am not 100% trusting of the git hub platform when it comes to finances, and easy relocation of projects. Thanks
