### ISSUE TITLE
Stripe Apps CLI prompt messages not showing up on Windows' git bash

### ISSUE THREAD

**Issue by htheodore-stripe** [stripe/stripe-apps#663] opened 2022-06-24 18:29 UTC
**Describe the bug**
Stripe Apps CLI prompt messages not showing up on Windows' git bash

**To Reproduce**
1. Run `stripe apps create helloworld` on git bash windows
2. Prompt message not showing up

**Expected behavior**
Prompt message should be shown

**Screenshots**

**CLI (please complete the following information):**
 - Stripe CLI: 1.8.11
 - Apps plugin: 1.2.4

**Additional context**

**Comment by htheodore-stripe** [comment] 2022-06-24 19:45
Issue on stripe-cli for more context: https://github.com/stripe/stripe-cli/issues/890

**Comment by gabrielhurley-stripe** [comment] 2024-06-27 15:40
Closing as a dupe of https://github.com/stripe/stripe-cli/issues/890 which has more investigation and context.

**Closed by gabrielhurley-stripe** 2024-06-27 15:40 UTC
Labels: bug, app-platform
