### ISSUE TITLE
`stripe.apps` is missing TypeScript definitions

### ISSUE THREAD

**Issue by paulasjes-stripe** [stripe/stripe-apps#711] opened 2022-08-10 11:04 UTC
**Describe the bug**
The `stripe-node` type definitions are missing types for `stripe.apps`. Running the following code (taken from the secret store docs) get you a type error:

![Screenshot 2022-08-10 at 1 01 30 PM](https://user-images.githubusercontent.com/46610432/183885716-7aa55c19-82ba-47ab-b500-f8c0c770e53e.png)

The code still runs fine, but you can't get rid of the error without using this workaround:

```js
// eslint-disable-next-line
// @ts-ignore
stripe.apps.secrets.create({
  scope: { type: 'user', user: userContext.id },
  name: 'secret_name',
  payload: 'secret value',
  expires_at: 1956528000  // optional
}).then(resp => console.log(resp));
```

**To Reproduce**
1. Copy paste the code from this docs guide into your editor: https://stripe.com/docs/stripe-apps/store-secrets#set-a-secret
2. See that there's a type error for `stripe.apps`

**Expected behavior**
`stripe-node` should have types for the `stripe.apps` object.

**Comment by jackokerman-stripe** [comment] 2022-08-10 16:08
Closing as a duplicate of #672. This will be fixed in the next SDK release.

**Closed by jackokerman-stripe** 2022-08-10 16:08 UTC
Labels: bug, needs-triage
